In [1]:
import numpy as np

In [4]:
arr = np.array((np.arange(5, 1000, 6), np.arange(7, 1000, 6)))

In [6]:
arr.T.flatten()

array([  5,   7,  11,  13,  17,  19,  23,  25,  29,  31,  35,  37,  41,
        43,  47,  49,  53,  55,  59,  61,  65,  67,  71,  73,  77,  79,
        83,  85,  89,  91,  95,  97, 101, 103, 107, 109, 113, 115, 119,
       121, 125, 127, 131, 133, 137, 139, 143, 145, 149, 151, 155, 157,
       161, 163, 167, 169, 173, 175, 179, 181, 185, 187, 191, 193, 197,
       199, 203, 205, 209, 211, 215, 217, 221, 223, 227, 229, 233, 235,
       239, 241, 245, 247, 251, 253, 257, 259, 263, 265, 269, 271, 275,
       277, 281, 283, 287, 289, 293, 295, 299, 301, 305, 307, 311, 313,
       317, 319, 323, 325, 329, 331, 335, 337, 341, 343, 347, 349, 353,
       355, 359, 361, 365, 367, 371, 373, 377, 379, 383, 385, 389, 391,
       395, 397, 401, 403, 407, 409, 413, 415, 419, 421, 425, 427, 431,
       433, 437, 439, 443, 445, 449, 451, 455, 457, 461, 463, 467, 469,
       473, 475, 479, 481, 485, 487, 491, 493, 497, 499, 503, 505, 509,
       511, 515, 517, 521, 523, 527, 529, 533, 535, 539, 541, 54

In [7]:
np.array((np.arange(5, 100, 6), np.arange(7, 100, 6))).T.flatten()

array([ 5,  7, 11, 13, 17, 19, 23, 25, 29, 31, 35, 37, 41, 43, 47, 49, 53,
       55, 59, 61, 65, 67, 71, 73, 77, 79, 83, 85, 89, 91, 95, 97])

In [13]:
n = 42
if n % 5 == 0:
    n = n-1
np.array((np.arange(5, n+1, 6), np.arange(7, n+1, 6))).T.flatten()

C:\Users\RoundPiano\AppData\Local\Temp\ipykernel_22200\4179578642.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array((np.arange(5, n+1, 6), np.arange(7, n+1, 6))).T.flatten()


array([array([ 5, 11, 17, 23, 29, 35, 41]),
       array([ 7, 13, 19, 25, 31, 37])], dtype=object)